### ISSUE TITLE
Page Reload on Tweet

### ISSUE THREAD

**Issue by kevinhaube** [muzam1l/tclone#2]
Expected action:  Tweeting adds the tweet to the top of the timeline

Current action:  Page reloads, showing login screen before verifying logged in, then shows timeline with tweet on top.

Info:  Mobile web (Safari) on iPhone XS Max running iOS 13.5

**Comment by kevinhaube** [comment]
Was this update deployed? I just gave it a test and still got the refresh that shows the trends page before loading the timeline.

Looking through the commit, I found this in your conditional for the `handleSubmit` function in the `Compose` component:

```
if (res.ok) {
     // let data = await res.json();
      this.props.history.push({ pathname: "/explore" });
      this.props.history.replace({ pathname: "/" });
}
```
I think this is what I'm experiencing, the quick jump to explore. You might be able to achieve the desired result by adding a loading state to `Posts` that can be controlled through the `Feed` layout.

**Comment by muzam1l** [comment]
Reloading whole page or flashing of landing is fixed, you might need to open new tab for changes to see effect(service worker)(maybe different behaviour on some devices).
Regarding this, Are you experiencing new type of issue. Because the code you mentioned is just the trick to do page _refresh_ of page(comps) than reloading as was before. It pushes /explore to history and then quickly replaces it with / forcing react-routes to refresh components, is this another issue or something?

**Comment by muzam1l** [comment]
```
function Root() {
  let { loading, error, isAuthenticated, user, logon } = useAuth();
  useEffect(() => {
    logon();
    // eslint-disable-next-line
  }, [])
  if (loading)
    return <div className="spinner"><Spinner /></div>
  else if (error)
    return <TryAgain fn={logon} message='Something went wrong, check you connection and try again' />
  else if (isAuthenticated && user)
    return <App />
  return <Landing />
}

```
This is upadated Root function in index, loading state is now added at index level(it was here what was causing those flashes on refresh) and this is triggered on manila refresh, everywhere else in app like posting, searching does causer reload at all. You might have seen old deploy from cache, check that again.

**Comment by kevinhaube** [comment]
I just tested it out again this morning, and it worked as described! Must have been the old deploy. 👍
